"""Workflow state values shared by domain and persistence layers."""
from enum import StrEnum


class ImportBatchStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PARSED = "PARSED"
    ALIGNED = "ALIGNED"
    DECIDED = "DECIDED"
    PROJECTING_BIG = "PROJECTING_BIG"
    PENDING_REVIEW = "PENDING_REVIEW"
    PARTIAL_FAILURE = "PARTIAL_FAILURE"
    FAILED = "FAILED"


class ReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PROJECTING_SMALL = "PROJECTING_SMALL"
    COMPLETED = "COMPLETED"


class ProjectionTarget(StrEnum):
    BIG_LIBRARY = "BIG_LIBRARY"
    SMALL_LIBRARY = "SMALL_LIBRARY"


class ProjectionState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    PERMANENT_FAILURE = "PERMANENT_FAILURE"


class OutboxState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    PERMANENT_FAILURE = "PERMANENT_FAILURE"
